name: Docker

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Build on more systems (respberry pi)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Build and Push
        if: success()
        uses: docker/build-push-action@v3
        with:
          push: true
          # Build for desktop and raspberry pi
          platforms: |
            linux/amd64
            linux/arm/v7
          # Create a versioned and a latest container
          tags: |
            blester125/ip-exporter:${{ steps.tagName.outputs.tag }}
            blester125/ip-exporter:latest
